name: SQL Migration and Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  migrate-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: Start SQL servers with Docker Compose
#      run: docker compose -f ./tests/docker-compose.yaml up -d

    - name: Start SQL servers with Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: ./tests/docker-compose.yaml

    - name: Wait for database initialization
      run: sleep 75  # MSSQL needs 60s sleep + buffer in its startup command

    - name: Run data migration with migrator.py
      run: python ./migrator.py

    - name: Run migration tests
      run: python ./tests/test2.py

#    - name: Tear down Docker Compose services
#      if: always()
#      run: docker compose -f ./tests/docker-compose.yaml down